Algorithms/Sort/bubble-sort.c, Data-Structures/Linked-List/Dbly_Llist.c
C implementation of **Doubly linked list**.
=> Created Dbly_Llist.c and bubble-sort.c

Algorithms/Sort/insertion-sort.c
simple code to implement insertion sort algorithm (in c) included in the sort subdirectory.
=> Insertion-sort.c inclusion

Algorithms/Sort/bubble-sort/bubble-sort.py, Algorithms/Sort/insertion-sort/insertion-sort.py, Algorithms/Sort/selection-sort/selection-sort.py
Try to implement some of those easiest, will work on those harder ones later.
=> Easy sorting algorithms in python3

contributing.md
=> contributing.md

Data-Structures/Linked-List/linkedlist.java, Data-Structures/Queues/queue.java, Data-Structures/Stack/stack.java, Data-Structures/Trees/tree.java
Added Java codes for following :-
1.) Tree
2.) Stack
3.) Queue
4.) LinkedList
=> Added DataStructure codes in JAVA

Algorithms/Search/binary-search/binary-search-sorted-array.cpp
A piece of code is added in binary-search.cpp to sort the array in ascending order.
=> sorting-array

Algorithms/Sort/heap-sort/heapSort.c
1. Corrected grammar and indentation
2. Changed `sz` to `size`. Just following proper variable naming convention.
2. Since `ar[]` and `size` are already declared to be global, there is no need to pass it in function.
4. Added some detail as to what `heapify()` and `heapSort()` does.
5. Removed array `b[]` because it had no use.
=> Please see the description.

Algorithms/Search/linear-search/linear-search.c
=> Added C implementation of linear search

Algorithms/Search/linear-search/linear-search.py
=> Added python implementation of linear search

Algorithms/Search/binary-search/binary-search.py
=> binary-search-python

Algorithms/Search/binary-search/binearysearch.java
=> binarysearch

Algorithms/Search/linear-search/linearsearch.java
=> linear search added

Algorithms/Search/binary-search/binary_search_sorted_array.c, Algorithms/Search/binary-search/binary_search_unsorted_array.c
=> binary search in c

Data-Structures/Stack/stack.py
An implementation of the stack data structure in python
=> Python implementation of Stack Data structure

Algorithms/DFS.py
Please, put the hacktoberfest label. Thank you :+1:
=> DFS algorithm in python

Algorithms/MST_PRIM.py
Implemented Minimum spanning tree using Prim's algorithm in python
=> add Minimum spanning tree using Prim's algorithm

Algorithms/LIS.py
Program to find largest increasing subsequence using dynamic programming with run time O(n*n)
=> add Program to find LIS

Algorithms/LCS.py
Program to find Longest Common Subsequence using dp
=> add Program to find LCS

Algorithms/Graph_Algorithms/TopologicalSort.cpp
=> Added topological sort in C++

Algorithms/Sort_Algorithms/Selection_Sort/selection-sort.c
=> Implemented Selection-Sorting Algorithm in C

Algorithms/Sort_Algorithms/Quick_Sort/Quick_Sort.py
@salman-bhai code follows pip 8 guidelines too. #53 Resolved for python.
=> Implemented Quick Sort in Python

Algorithms/Sort_Algorithms/Quick_Sort/Quick.cpp, Algorithms/Sort_Algorithms/Quick_Sort/Quicksort.h
=> Added Quick Sort Algorithm C++

Algorithms/Sort_Algorithms/Quick_Sort/quickSort.c
resolved #53 in the C language
=> Added quicksort algorithm in C

Data-Structures/Trees/AVL_Trees/AVLTree.c
=> Added AVL Tree implementation in C

Algorithms/Sort_Algorithms/Quick_Sort/QuickSort.java, Data-Structures/Trees/AVL_Trees/README.md
I have written a Java implementation of the QuickSort algorithm with documentation. An array is statically defined and sorted using a transparent QuickSort implementation.
=> Java quicksort

Algorithms/Sort_Algorithms/Bubble_Sort/BubbleSort.java
A file named BubbleSort.java has been added which possesses two methods. The main driver reads in an array of integers from the console, then sorts them using our bubble sort method named "sort." Finally, after the array has been sorted, the sorted array is output on the console.
=> Added a Java implementation of the Bubble Sort algorithm!

Algorithms/Sort_Algorithms/Selection_Sort/selectionsort.java
Implementation of Selection Sort in Java #55
=> Selection Sort

Algorithms/Sort_Algorithms/Bucket_Sort/Bucket_Sort.py
Please Close #49 I have implemented it.
Thanks!
=> Added Python Bucket Sort Algorithm

Algorithms/Sort_Algorithms/Radix_Sort/Radix_Sort.py
=> Added Radix Sort Algo in Python

Data-Structures/Binary_search_tree/binary_search_tree.py
Binary Search Tree in Python added #66 resolved in Python
=> Added Binary Search Tree in Python

Data-Structures/Linked_List/Singly_Linked_List/linked_list.c
=> Linked List In C Language

Algorithms/Graph_Algorithms/DFS/DFS.cpp
=> Add dfs implementation in c++

Algorithms/Graph_Algorithms/Kruskal's_MST/KRUSKAL.cpp
#46 
Signed-off-by: Jedian <jmb15@c3sl.ufpr.br>
=> Added Kruskal in cpp

Algorithms/Sort_Algorithms/Merge_Sort/mergeSort.cpp
=> Add merge sort c++ source code

Algorithms/Sort_Algorithms/Radix_Sort/Radix_Sort.cpp
=> Add Radix sort implementation in C++

Algorithms/Graph_Algorithms/BFS/BFS.cpp
=> Add bfs source code in c++

Algorithms/Graph_Algorithms/BFS/BFS.java
=> Added BFS for Java

Algorithms/Graph_Algorithms/BFS/BFS.py
=> Added BFS for Python

Data-Structures/Disjoint_Sets/DisjointSet.c
Disjoint Set  Data Structure added. Resolves #61 in C.
=> Disjoint Set Datastructure in C added

Algorithms/Graph_Algorithms/Kruskal's_MST/KRUSKAL.c
Kruskal in C added. #46 Solved in C
=> Kruskal in C

Algorithms/Sort_Algorithms/Heap_Sort/heapsort.py
I have added a generic HeapSort function in Python language.  #50
=> Added HeapSort.py

Data-Structures/Trees/AVL_Trees/AVLTree.py
Provided is an implementation of an AVL tree in Python. #65
=> Python implementation of an AVL tree

Algorithms/Graph_Algorithms/Bellman_Ford/Bellman–Ford.cpp
#103 
Bellman Ford Algorithm implement in C++
=> Add Bellman-Ford algorithm

Data-Structures/Trees/Binary_Trees/binary_tree.py
Implementing a binary tree data structure in Python. #67
=> Python Binary Tree Data Structure

Algorithms/Graph_Algorithms/Floyd_Warshall/Floyd-Warshall.cpp
Floyd-Warshall added in cpp.
Reference #45
=> Floyd-Warshall added in cpp

Data-Structures/Linked_List/Circular_Linked_List/circular_linked_list.cpp
Implemented circular linked lists in C++ using templates and pointers
=> Added Circular Linked Lists in C++

Algorithms/Graph_Algorithms/Prim's_MST/Prim.java
=> Added Prim in Java

Algorithms/Graph_Algorithms/Bellman_Ford/Bellman_Ford.java
=> Add Bellman Ford implementation in Java

Algorithms/Sort_Algorithms/Bubble_Sort/README.md
=> Update Readme.md for Bucket Sort #74

Algorithms/Graph_Algorithms/Bellman_Ford/bellman-ford.c, Data-Structures/Binary_search_tree/binary-search-tree-cpp.cpp, Data-Structures/Trees/AVL_Trees/avl.cc
=> Add Bellman ford implementation in c

Algorithms/Graph_Algorithms/Prim's_MST/prims.c, Algorithms/Graph_Algorithms/dsu.cpp
add disjoint set union in cpp #61
=> add disjoint set union in cpp

Algorithms/Sort_Algorithms/Radix_Sort/radixinc.c, Data-Structures/Linked_List/Circular_Linked_List/circular.c, Data-Structures/Linked_List/Doubly_Linked_List/doubly.c
=> Circular by me

Algorithms/Sort_Algorithms/Heap_Sort/README.md
Added README for Heap Sort. #74
=> Added Heap sort README

Algorithms/Sort_Algorithms/Shell_Sort/ShellSort.py, Data-Structures/Trees/AVL_Trees/AVL.java
=> AVL tree in java and Shell Sort in Python

Algorithms/Sort_Algorithms/Shell_Sort/ShellSort.py, Data-Structures/Binary_search_tree/BST.java
=> Created BST in java.

Algorithms/Sort_Algorithms/Radix_Sort/RadixSort.java, Algorithms/Sort_Algorithms/Shell_Sort/shell_sort.cpp
=> radix sort in java

Algorithms/Sort_Algorithms/Insertion_Sort/InsertionSort.java, Algorithms/Sort_Algorithms/Shell_Sort/shell_sort.cpp
=> #51 insertion sort in java

Algorithms/Graph_Algorithms/Kruskal's_MST/kruskal.java
=> Created java code for kruskal's algorithm.

Algorithms/Graph_Algorithms/Bellman_Ford/Readme.md, Algorithms/Graph_Algorithms/Floyd_Warshall/README.md, Algorithms/Graph_Algorithms/Prim's_MST/MST_prims.cpp, Algorithms/Sort_Algorithms/Radix_Sort/README.md
=> Prims_MST.cpp Bellman_Ford Floyd_Warshall _Radix added

Algorithms/Graph_Algorithms/Bellman_Ford/bellman-ford.c, Algorithms/Sort_Algorithms/Shell_Sort/shell-sort.cpp, Data-Structures/Binary_search_tree/binary-search-tree-cpp.cpp, Data-Structures/Trees/AVL_Trees/avl.cc
=> SHell Sort in C++

Algorithms/Sort_Algorithms/Radix_Sort/Radix_Sort.java, Algorithms/Sort_Algorithms/Shell_Sort/Shell_Sort.cpp, Algorithms/Sort_Algorithms/Tree_Sort/Tree_Sort.cpp
=>  Added Radix sort implementation in java 

Algorithms/Sort_Algorithms/Shell_Sort/Shell_Sort.cpp, Algorithms/Sort_Algorithms/Tree_Sort/Tree_Sort.cpp
=> Added Tree Sort implementation in C++

Algorithms/Sort_Algorithms/Shell_Sort/ShellSort.py, Data-Structures/Trees/AVL_Trees/AVL.java, Data-Structures/Tries/Trie.cpp
=> Trie.cpp SHellSort.py AVL.java

Data-Structures/Tries/trie.c, Data-Structures/Tries/trie.java
=> created trie.c

Data-Structures/Linked_List/Circular_Linked_List/circular_linked_list.java, Data-Structures/Tries/trie.java
=> implemented circular linked list in java

Data-Structures/Linked_List/Circular_Linked_List/circular_linked_list.py, Data-Structures/Tries/trie.java
=> implemented circular linked list in python

Data-Structures/Trees/Binary_Trees/binarytree.java, Data-Structures/Tries/trie.java
=> imlemented binary tree in java

Algorithms/Graph_Algorithms/Dijkstra/Dijkstra.py
#44 ......Dijkstra's Algo in Python
=> Create Dijkstra.py 

Algorithms/Graph_Algorithms/Kruskal's_MST/KRUSAL.py
=> Add Kruskal in python

Data-Structures/Tries/Trie.py
Trie data structure in python #68
=> Trie data structure in python

Algorithms/Graph_Algorithms/Kruskal's_MST/KRUSAL.py, Algorithms/Sort_Algorithms/Heap_Sort/heapsort.java, Algorithms/Sort_Algorithms/Topological_Sort/TopologicalSort.java
=> Topological

Algorithms/Sort_Algorithms/Tree_Sort/TreeSort.java, Data-Structures/Tries/Trie.py
=> Akshaj5 patch 2

Algorithms/Sort_Algorithms/Tree_Sort/TreeSort.py, Data-Structures/Tries/Trie.py
=> Tree Sort in Python

Algorithms/Graph_Algorithms/Kruskal's_MST/KRUSAL.py, Algorithms/Sort_Algorithms/Heap_Sort/heapsort.java, Algorithms/Sort_Algorithms/Topological_Sort/TopologicalSort.java, Data-Structures/Disjoint_Sets/DisjointSet.java
=> Disjointset

Data-Structures/Disjoint_Sets/DisjointSet.py, Data-Structures/Tries/Trie.py
Disjoint-Set implementation in python #61
=> Pythondisjointset

Doubly_Linked_List.py
=> Implemented Doubly Linked List in Python

Doubly_Linked_List.py, Floyd_Warshall.c
=> Implemented Floyd Warshall Algorithm in C

Algorithms/Graph_Algorithms/Bellman_Ford/Readme.md, Algorithms/Graph_Algorithms/Floyd_Warshall/README.md, Algorithms/Graph_Algorithms/Prim's_MST/MST_prims.cpp, Algorithms/Sort_Algorithms/Radix_Sort/README.md
=> Readme.md for radix sort

Algorithms/Graph_Algorithms/Dijkstra/dijkstra.cpp
=> Add dijkstra algorithm implementation in c++

Algorithms/Graph_Algorithms/Bellman_Ford/bellman-ford.c, Algorithms/Sort_Algorithms/Selection_Sort/README.md, Data-Structures/Binary_search_tree/binary-search-tree-cpp.cpp, Data-Structures/Trees/AVL_Trees/avl.cc
solved issue of readme selection sort #74
=> Bashtech123 patch 4

Algorithms/Sort_Algorithms/Shell_Sort/README.md
Make README for Shell Sort #75
=> Update Shell Sort  README

Algorithms/Search_Algorithms/Linear_Search/README.md
Added README.md for Linear Search
=> README.md for Linear Search

Data-Structures/Linked_List/Doubly_Linked_List/DoublyLinkedListImpl.java
Add implementation of Doubly Linked List in Java. #63
=> Add Doubly Linked List in Java

sort.md
=> README.md for Insertion sort is ready and is in file named sort.md in branch insertion

Algorithms/Graph_Algorithms/Floyd_Warshall/FloydWarshall.java
=> Implement Floyd-Warshall in Java

Algorithms/Sort_Algorithms/Topological_Sort/TopologicalSort.py
=> Add topological sorting in Python

Algorithms/Sort_Algorithms/Tree_Sort/TreeSort.c
Add C implementation of Tree Sort. #58
=> Add TreeSort.c

Algorithms/Sort_Algorithms/Merge_Sort/README.md, Algorithms/Sort_Algorithms/Quick_Sort/README.md, quicksort.md
=> README.md for quick sort ready

Algorithms/Graph_Algorithms/Prim's_MST/Prim.c
Uploaded implementation of Prim's MST in C
=> Added Prim.c

Algorithms/Graph_Algorithms/Kruskal's_MST/README.md
=> Add ReadMe for Kruskal algorithm to find MST

Algorithms/Sort_Algorithms/Tree_Sort/README.md
=> Add ReadMe for Tree sort

Algorithms/Sort_Algorithms/Topological_Sort/README.md
=> Readme for topological sort

Algorithms/Graph_Algorithms/Prim's_MST/README.md
=> Add ReadMe for Prim's MST

Data-Structures/Stacks/tests/test_stack.py
This PR adds unit tests for the stack data structure implemented in python.
=> Add unit tests for python data structure

Algorithms/Graph_Algorithms/Dijkstra/README.md
=> Add ReadMe for Dijkstra algorithm

Algorithms/Search_Algorithms/Ternary_Search/README.md, Algorithms/Search_Algorithms/Ternary_Search/ternary-search.cpp
Add ternary search along with readme.
=> Add ternary search
